name: Build Release Binaries

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download Go modules
        run: go get ./...

      - name: Build the release binaries
        run: .github/workflows/build.sh ${{ github.event.release.tag_name }}

      - name: Upload Release Assets
        run: |
          for tarball in *.tar.gz; do
            curl \
              -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-type: application/octet-stream" \
              --data-binary @$tarball \
              "https://uploads.github.com/repos/ngharrington/simpleenv/releases/${{ github.event.release.id }}/assets?name=$tarball"
          done
